blog/urls.py
from django.urls import path
from . import views



urlpatterns = [
    path('post/<str:slug>/edit/', views.post_edit, name='post_edit'),
    path('category/<str:slug>/', views.category, name='category'),
    path('post/new/', views.post_new, name='postnew'),
    path('post/<str:slug>/', views.post_detail, name='post_detail'),
    path('login/', views.user_login, name='user-login'),
    path('signup/', views.signup, name='sign-up'),
    path('cust-logout/', views.signout, name='log-out'),
    path('user/<int:user_id>/', views.userdetail, name='userdetail'),
    path('upload-profile-photo/', views.upload_profile_photo, name='uploadprofilephoto'),
    path('comment/', views.comment, name='comment'),
    path('reply/', views.reply, name='reply'),
    path('', views.post_list, name='post_list'),
    
]

merge/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [

    path('admin/', admin.site.urls),
    path('polls/', include('polls.urls')),
    path('', include('blog.urls')),
    path('home/', include('home.urls')),
    
]

if settings.DEBUG:    
 urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

polls/urls.py
from django.urls import path

from . import views



app_name = "polls"
urlpatterns = [
    path("polls/", views.IndexView.as_view(), name="index"),
    path("<int:pk>/", views.DetailView.as_view(), name="detail"),
    path("<int:pk>/results/", views.ResultsView.as_view(), name="results"),
    path("<int:question_id>/vote/", views.vote, name="vote"),
    

]

blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import AbstractUser
from django.contrib.auth.models import User
from autoslug import AutoSlugField
from django.utils.timezone import now





class User(AbstractUser):
    email = models.EmailField(unique=True)
    image = models.ImageField(upload_to="my_images", blank=True,null=True)
    city = models.CharField(max_length=255, blank=True, null=True)
    state= models.CharField(max_length=255, blank=True, null=True)
    firstname= models.CharField(max_length=255, blank=True, null=True)
    lastname= models.CharField(max_length=255, blank=True, null=True)
    SearchableFields = ['title','author']
 
    REQUIRED_FIELDS =[]
    # USERNAME_FIELD = 'email'

    def publish(self):
        self.published_date = timezone.now()
        self.save()

    
    


class Tags(models.Model):
    name = models.CharField(max_length=200, blank=True, null=True)
    slug = AutoSlugField( max_length=300, unique=True,populate_from='name')
    SearchableFields = ['name']
    FilterFields = ['name']
    def __str__(self): 
        return self.name


class Category(models.Model):
    name = models.CharField(max_length=200, blank=True, null=True)
    slug = AutoSlugField( max_length=300, unique=True,populate_from='name')
    SearchableFields = ['name']
    FilterFields = ['name']
    def __str__(self): 
        return self.name

    
class Post(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE,null=True)
    title = models.CharField(max_length=200)
    text = models.TextField()
    created_date = models.DateTimeField(default=timezone.now)
    published_date = models.DateTimeField(blank=True, null=True)
    thumbnail = models.ImageField(upload_to="my-thumbnail", blank=True, null=True)
    feature = models.ImageField(upload_to="my-feature", blank=True, null=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, blank=True, null=True)
    tag = models.ManyToManyField(Tags, blank=True)
    slug = AutoSlugField( max_length=300, unique=True,populate_from='title')
    SearchableFields = ['title']
    FilterFields = ['title']

    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def __str__(self):
        return self.title

class Comment(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE,null=True, blank=True)   
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    name = models.CharField(max_length=250)
    body = models.TextField(max_length=500)
    published_date = models.DateTimeField( default=now )
    parent = models.ForeignKey('self', on_delete=models.CASCADE, null = True, blank = True)
    SearchableFields = ['User','post']
    FilterFields = ['post']


    def __str__(self):
        return f'Comment by {self.user} on {self.post}'
        
class Reply(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE,null=True, blank=True)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    comment = models.ForeignKey(Comment, on_delete=models.CASCADE, null=True ,blank= True)
    body = models.TextField(max_length=500)
    time =models.DateTimeField(default=now)
    SearchableFields = ['User','post','body']
    FilterFields = ['post']

def __str__(self):
    return f'comment by {self.user} on {self.post} in {self.body}'

blog/forms.py
from django import forms


from .models import Post, User, Comment, Reply
class PostForm(forms.ModelForm):

    class Meta:
        model = Post
        fields = ('author', 'title', 'text','thumbnail','feature','category', 'tag')




class UserForm(forms.ModelForm):
    email = forms.EmailField(
        label='Email',
    widget=forms.EmailInput(attrs={'class': 'col-10', 'id': 'email', 'name': 'email'}))
    
    password=forms.CharField(
        label="Password",
        widget=forms.PasswordInput(attrs={'class': 'col-10', 'id': 'password', 'name': 'password'}))
    
    class Meta:
        model = User                
        fields = ("email","password",)

class ProfilePhotoForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['image']

    

class SignupForm(forms.ModelForm):
    username=forms.CharField(
        label='User Name',
        widget=forms.TextInput(attrs={'class': 'col-10', 'id': 'username', 'name': 'username'})
    )

    firstname=forms.CharField(
        label='First name',
        widget=forms.TextInput(attrs={'class': 'col-10', 'id': 'firstname', 'name': 'firstname'}),
    )
    lastname=forms.CharField(
        label='last name',
        widget=forms.TextInput(attrs={'class': 'col-10', 'id': 'lastname', 'name': 'lastname'}),
    )
    
    email = forms.EmailField(
        label='Email',
        widget=forms.EmailInput(attrs={'class': 'col-10', 'id': 'email', 'name': 'email'})
    )
    

    password=forms.CharField(
        label="Password",
        widget=forms.PasswordInput(attrs={'class': 'col-10', 'id': 'password', 'name': 'password'})
    )
    class Meta:
        model = User
        fields = ("username","firstname","lastname","email","password","password")
    





class CommentForm(forms.ModelForm):
    body=forms.CharField(
        label='Comment',
        widget=forms.TextInput(attrs={'class': 'col-10', 'id': 'body', 'name': 'body'})
    )
    class Meta:
        model = Comment
        fields = ['body']
    

class ReplyForm(forms.ModelForm):
    body=forms.CharField(
        widget=forms.TextInput(attrs={'class': 'col-10', 'id': 'body', 'name': 'body'})

    )
    class Meta:
        model = Reply
        fields = ['body']

blog/views.py
from django.shortcuts import render, get_object_or_404
from django.utils import timezone
from .models import Post,User, Comment
from django.contrib.auth import authenticate, login, logout
from .forms import PostForm,  UserForm, SignupForm,ProfilePhotoForm,CommentForm , ReplyForm
from django.shortcuts import redirect
from django.contrib import messages




def post_list(request):
    posts = Post.objects.filter(published_date__lte=timezone.now()).order_by('published_date')
    return render(request, "blog/post_list.html", {"posts": posts})

def category(request,slug):
    
    categories = Post.objects.filter(category__slug=slug)
    return render(request, "blog/category.html", {"categories": categories})

# i ama not use these function//

# def tag(request, slug):
#     print(slug)
#     if slug:
#         tags = Post.objects.filter(tag__slug=slug).order_by("published_date")
#     else:
#         tags = Post.objects.all().order_by("published_date")
#     return render(request, "blog/tag.html", {"tags": tags})

def comment(request):
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            post = get_object_or_404(Post, id=request.POST.get('post_id'))
            comment.post = post
            comment.user = request.user
            parent_id = request.POST.get('parent_id')
            if parent_id:
                comment.parent = get_object_or_404(Comment, id=parent_id)
            comment.save()
            return redirect('post_detail', slug=post.slug)
    return redirect('post_list' )


def reply(request):
    comment_id = request.POST.get('comment_id')
    parent_comment = get_object_or_404(Comment, id=comment_id)
    post = parent_comment.post
    if request.method == 'POST':
        print(request.POST)
        form = ReplyForm(request.POST)
        if form.is_valid():
            reply = form.save(commit=False)
            reply.post = post
            reply.comment = parent_comment
            reply.user = request.user  
            reply.save()
            return redirect('post_detail', slug=post.slug)
    else:
        form = ReplyForm()
    return render(request, 'blog/post_detail.html', {'form': form, 'post': post,'parent_comment': parent_comment,})





def post_detail(request, slug):
    post = get_object_or_404(Post,slug=slug)
    comments = Comment.objects.filter(post=post).select_related('user','parent')
    form = CommentForm()
    context= {
        'post':post,
        'form':form,
        'comments':comments,
        'user':request.user,

    }
    return render(request, 'blog/post_detail.html', context)

def post_new(request):
    if request.method == "POST":
        form = PostForm(request.POST,request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
        
            post.published_date = timezone.now()

            post.save()
            return redirect('post_detail', slug=post.slug)
    else:
        form = PostForm()
    return render(request, 'blog/post_edit.html', {'form': form})
 
def post_edit(request, slug):
    post = get_object_or_404(Post, slug=slug)
    if request.method == "POST":
        form = PostForm(request.POST, request.FILES, instance=post,)
        if form.is_valid():
            post = form.save(commit=False)
            
            post.published_date = timezone.now()
            post.save()
            return redirect('post_detail',slug=post.slug)
    else:
        form = PostForm(instance=post)
    return render(request, 'blog/post_edit.html', {'form': form})

def user_login(request):
    form=UserForm()
    
    if request.method == 'POST':
        username = request.POST.get('email')
        password = request.POST.get('password')
        
        print(username,password)
        user = authenticate(request, username=username, password=password)
        
        if user is not None:
            print('good job')
            login(request, user)
            return redirect('/',"Welcomemessage= {}!".format(request.user.username))
            
    return render(request,"blog/userlogin.html", {"form":form})

def signup(request):
    if request.method=="POST":
        username=request.POST["username"]
        fname=request.POST["firstname"]
        lname=request.POST["lastname"]
        email=request.POST["email"]
        password=request.POST["password"]
        myuser = User.objects.create_user(username=username, email=email, password=password,firstname=fname,lastname=lname)
        myuser.save()
        messages.success(request,"successful!")

        return redirect('/login/')
    else:
        form=SignupForm()
    return render(request,"blog/userlogin.html",{"form":form})

def signout(request):
    print(1)
    logout(request)
    return redirect('/login')



def userdetail(request, user_id):
    user = get_object_or_404(User, pk=user_id)
    
    return render(request, 'blog/userdetail.html', {'user': user})

def upload_profile_photo(request):
    if request.method == 'POST':
        form = ProfilePhotoForm(request.POST, request.FILES, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect('post_list') 
    else:
        form = ProfilePhotoForm(instance=request.user)
    
    return render(request, 'blog/upload_profile_photo.html',{'form':form})  

blog/templates/blog/base.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
    <title>Django Girls Blog</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext">
    <link rel="stylesheet" href="{% static 'css/blog.css' %}">
    <style>
        body {
            font-family: 'Lobster', sans-serif;
            background-color: rgb(0, 128, 128);
        }
        .navbar-brand {
            font-size: 2rem;
            
        }
        .navbar-nav .nav-link {
            font-size: 1.2rem;
            
        }
        .dropdown-menu .dropdown-item {
            font-size: 1rem;
        }
    </style>
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container">
            <a class="navbar-brand" href="{% url 'post_list' %}">Blog</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'postnew' %}">
                            {% include './icons/file-earmark-plus (1).svg' %}
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'polls:index' %}">Polls</a>
                    </li>
                    {% if request.user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'log-out'%}">Logout</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'userdetail' user_id=request.user.id %}">Welcome, {{ request.user.first_name }}!</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'uploadprofilephoto' %}">photo</a>
                    </li>
                    {% else %}
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            Login
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <li><a class="dropdown-item" href="{% url 'user-login' %}">Login</a></li>
                            <li><a class="dropdown-item" href="{% url 'sign-up'%}">Sign Up</a></li>
                        </ul>
                    </li>
                    {% endif %}
                </ul>
                {% if request.user.is_authenticated %}
                <ul class="navbar-nav">
                    {% for user in User %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'user_detail' user_id=user.id %}">{{ user.username }}</a>
                    </li>
                    {% endfor %}
                </ul>
                {% endif %}
            </div>
        </div>
    </nav>

    <main class="container mt-4">
        <div class="row">
            <div class="col">
                {% block content %}
                {% endblock %}
            </div>
        </div>
    </main>

    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
</body>

</html>

blog/templates/blog/category.html
{% extends 'blog/base.html' %}
{% block content %}
<div style="display:flex; gap:20px; flex-wrap: wrap;">
    {% for post in categories %}
    <div class="card" style="width: 20rem;">
        <img class="card-img-top" src="{% if post.feature %}{{ post.feature.url }}{% endif %}" alt="Card image cap" width=200px height=200px>
        <div class="card-body">
            <h4 class="card-title"><a href="{% url 'post_detail' slug=post.slug %}">{{ post.title }}</a></h4>
            <div style="display:flex; gap:30px">
                <p><b>Category:-&nbsp;<a href="{% url 'category' slug=post.category.slug %}">{{ post.category }}</a></b></p>
            </div>
            <p class="card-text">{{ post.text|truncatewords:30 }}<br>
                <b>Published At:-&nbsp;</b>{{ post.published_date|date:"Y-m-d" }}<br>    
            </p>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock %}

blog/templates/blog/post_detail.html
{% extends 'blog/base.html' %}
{% block content %}
{% if request.user.is_authenticated %}
<div class="container mt-4">
    
    <article class="post card p-4 mb-4 shadow-sm">
        <div class="d-flex align-items-center mb-3">
            <img class="rounded-circle border border-secondary me-3"
                src="{% if post.thumbnail %}{{ post.thumbnail.url }}{% endif %}" alt="Thumbnail"
                style="height: 60px; width: 60px;">
            <h2 class="m-0">{{ post.title }}</h2>
        </div>
        <div class="text-center mb-3">
            <img src="{% if post.feature %}{{ post.feature.url }}{% endif %}" alt="feature" class="img-fluid"
                style="max-height: 400px; max-width: 100%;">
        </div>
        <p><b>Category: </b><a href="{% url 'category' slug=post.slug %}">{{ post.slug }}</a></p>
    
        <p>{{ post.text|truncatewords:30 }}</p>
        <p><b>Published At: </b>{{ post.published_date|date:"Y-m-d" }}<br>
            <strong>Published By: </strong>{{ post.author }}
        </p>

        
        <aside class="actions text-end">
            <a class="btn btn-outline-secondary" href="{% url 'post_edit' slug=post.slug %}">
                {% include './icons/pencil-fill.svg' %} Edit
            </a>
        </aside>
    </article>

    
    <h4>Add Comment Here</h4>
    <form action="{% url 'comment' %}" method="post" enctype="multipart/form-data" class="mb-4">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="hidden" name="post_id" value="{{ post.id }}">
        <button type="submit" class="btn btn-primary">Post Comment</button>
    </form>

    <div class="comments-section">
        <h5>Comments</h5>
        {% for comment in comments %}
        <div class="card p-3 mb-3">
            <div class="d-flex justify-content-between align-items-center">
                <strong>{{ comment.user.username|title }}</strong>
                <small class="text-muted">{{ comment.timestamp }}</small>
            </div>
            <div class="mt-2">{{ comment.body }}</div>
            <div class="reply mx-0">
                <button class="btn btn-sm btn-primary" type="button" data-bs-toggle="collapse"
                    data-bs-target="#replyBox{{comment.id}}" aria-expanded="false"
                    aria-controls="replyBox{{comment.id}}">
                    Reply
                </button>
                <div class="collapse" id="replyBox{{comment.id}}">
                    <div class="card card-body my-2">
                        <form action="{% url 'reply'%}" method="post">
                            {% csrf_token %}
                            {{ form.as_p }}
                            <input type="hidden" name="comment_id" value="{{ comment.id }}">
                            <button type="submit">Post Reply</button>
                        </form>

                        {% for reply in comment.comment_replies.all %}
                        <div class="row my-3">
                                <strong>{{ reply.user.username|title }}</strong> at {{ reply.time }}
                                <div>{{ reply.body }}</div>
                            </div>
                        </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    </div>
    
</div>

</div>

<p>No comments yet.</p>
{% endfor %}
</div>
</div>


{% else %}
<div class="container mt-4">
    <article class="post card p-4 mb-4 shadow-sm">
        <div class="d-flex align-items-center mb-3">
            <img class="rounded-circle border border-secondary me-3"
                src="{% if post.thumbnail %}{{ post.thumbnail.url }}{% endif %}" alt="Thumbnail"
                style="height: 60px; width: 60px;">
            <h2 class="m-0">{{ post.title }}</h2>
        </div>
        <div class="text-center mb-3">
            <img src="{% if post.feature %}{{ post.feature.url }}{% endif %}" alt="feature" class="img-fluid"
                style="max-height: 400px; max-width: 100%;">
        </div>
        <p><b>Category: </b><a href="{% url 'category' slug=post.category.slug %}">{{ post.category }}</a></p>
    
        <p>{{ post.text|truncatewords:30 }}</p>
        <p><b>Published At: </b>{{ post.published_date|date:"Y-m-d" }}<br>
            <strong>Published By: </strong>{{ post.author }}
        </p>
        <div class="comments-section">
            <h5>Comments</h5>
            {% for comment in comments %}
            <div class="card p-3 mb-3">
                <div class="d-flex justify-content-between align-items-center">
                    <strong>{{ comment.user.username|title }}</strong>
                    <small class="text-muted">{{ comment.timestamp }}</small>
                </div>
                <div class="mt-2">{{ comment.body }}</div>
                <div class="reply mx-0">
                    <button class="btn btn-sm btn-primary" type="button" data-bs-toggle="collapse"
                        data-bs-target="#replyBox{{comment.id}}" aria-expanded="false"
                        aria-controls="replyBox{{comment.id}}">
                        Reply
                    </button>
                    <div class="collapse" id="replyBox{{comment.id}}">
                        <div class="card card-body my-2">
                            <form action="{% url 'reply'%}" method="post">
                                {% csrf_token %}
                                {{ form.as_p }}
                                <input type="hidden" name="comment_id" value="{{ comment.id }}">
                                <button type="submit">Post Reply</button>
                            </form>
    
                            {% for reply in comment.comment_replies.all %}
                            <div class="row my-3">
                                    <strong>{{ reply.user.username|title }}</strong> at {{ reply.time }}
                                    <div>{{ reply.body }}</div>
                                </div>
                            </div>
                            {% endfor %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
        
    </div>
    
    </div>
    
    <p>No comments yet.</p>
    {% endfor %}
    </div>
    </div>
{% endif %}
{% endblock %}

blog/templates/blog/post_edit.html
{% extends 'blog/base.html' %}

{% block content %}
    <h2>New post</h2>
    <form method="POST" enctype="multipart/form-data"  class="post-form">{% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="save btn btn-secondary">Save</button>
    </form>
{% endblock %}

blog/templates/blog/post_list.html
{% extends 'blog/base.html' %}
{% block content %}
<div class="row">
    {% for post in posts %}
    <div class="col-12 col-md-12 col-lg-4 mb-4">
        <div class="card" style="width: 100%;">
            <img class="card-img-top" src="{% if post.feature %}{{ post.feature.url }}   {% endif %}" alt="Card image cap"
                style="width: 100%; height: 260px;">
            <div class="card-body">
                <h4 class="card-title">
                    <a href="{% url 'post_detail' slug=post.slug %}">{{ post.title }}</a>
                </h4>
                  <div style="display:flex; gap:30px">
                    <p><b>Category:-&nbsp;<a href="{% url 'category' slug=post.slug %}">{{ post.category}}</a></b></p>
                </div>

                <p class="card-text">{{ post.text|truncatewords:30 }}<br>
                    <b>Published At:-&nbsp;</b>{{ post.published_date|date:"Y-m-d" }}<br>
                    <strong>Published By:-&nbsp;</strong>{% if post.author %}{{ post.author }}{% endif %}
                </p>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
<!-- </div> -->
{% endblock %}

blog/templates/blog/signup.html
{% extends 'blog/base.html' %}
{% block content %}
<div class="card ">
    <div class="card-header">
     SignUP 
    </div>
    <div class="card-body">
            {% for field in form %}
        <div class="row mt-3">
            <label class="col-2" for="{{ field.id_for_label }}">{{ field.label }}</label>
            {{ field }}
        </div>
            {% endfor %}
    
        <div style="float: right ;padding: auto;" class="mt-3" >
                <button type="submit" class="btn btn-primary">SignUP</button>
        </div>
    </div>    
</div>


{% endblock %}

blog/templates/blog/tag.html
{% extends 'blog/base.html' %}
{% block content %}
<div style="display:flex; gap:20px; flex-wrap: wrap;">
    {% for post in tags %}
    <div class="card" style="width: 20rem;">
        <img class="card-img-top" src="{% if post.feature %}{{ post.feature.url }}{% endif %}" alt="Card image cap" width=200px height=200px>
        <div class="card-body">
            <h4 class="card-title"><a href="{% url 'post_detail' slug=post.slug %}">{{ post.title }}</a></h4>
            <div style="display:flex; gap:30px">
                <p><b>category:-&nbsp;<a href="{% url 'category' slug=post.category.slug %}">{{ post.category }}</a></b></p>
            </div>
            <p class="card-text">{{ post.text|truncatewords:30 }}<br>
                <b>Published At:-&nbsp;</b>{{ post.published_date|date:"Y-m-d" }}<br>
                <b>Tags:-</b>
                {% for tag in post.tag.all %}
                <a href="{% url 'tag' slug=tag.slug %}"><small>{{ tag.name }} <b>||</b></small></a>
                {% endfor %}
            </p>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock %}

blog/templates/blog/upload_profile_photo.html
{% extends 'blog/base.html' %}
{% block content %}


<h2>Upload Profile Photo</h2>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Upload</button>
    </form>

    {% if user.profile_photo %}
        <img src="{{ user.profile_photo.url }}" alt="Profile Photo" style="max-height:100px ;">
    {% endif %}

  
{% endblock %}

blog/templates/blog/userdetail.html
{% extends 'blog/base.html' %}
{% block content %}

<div class="card card-body">
   
    <h1>User Detail's</h1>
     {% if user.image %}
     <img src="{{ user.image.url}}" alt="Profile Photo" width="100px" height="100px"><br>
    

    <p>Username: {{ user.username }}</p>
    <p>Email: {{ user.email }}</p>
    <p>Name: {{ user.firstname }}  {{ user.lastname }}</p>
    {% endif %}   
</div>
{% endblock %}

blog/templates/blog/userlogin.html
{% extends 'blog/base.html' %}
{% block content %}
<div class="card ">
    <div class="card-header">
     User Login 
    </div>
    <div class="card-body ">
        <form action="" method="post" class="mt-3">
            {% csrf_token %}
            {% for field in form %}
                <div class="row mt-3">
                    <label class="col-2" for="{{ field.id_for_label }}">{{ field.label }}</label>
                    {{ field }}
                </div>
            {% endfor %}
            
            <div style="float: right ;padding: auto;" class="mt-3" >
                <button type="submit" class="btn btn-primary">login</button>
            </div>
        </form>
        
    </div>
  </div>

{% endblock %}